services:
  linux:
    build:
      context: ./docker/linux
    container_name: ${APP_NAME}_linux
    hostname: ${APP_NAME}_linux
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./opt:/opt
      - ./log:/var/log
      - ${APP_PATH_WWW}:/var/www

  nginx:
    image: nginx:${NGINX_VERSION:-1.19}-alpine
    container_name: ${APP_NAME}_nginx
    depends_on:
      - php
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
      - NGINX_HOST=${NGINX_HOST:-localhost}
      - NGINX_ROOT=${NGINX_ROOT:-/var/www}
    hostname: ${APP_NAME}_nginx
    ports:
      - "${NGINX_PORT_HTTP:-80}:80"
      - "${NGINX_PORT_HTTPS:-443}:443"
    volumes:
      - ./opt:/opt
      - ./log:/var/log
      - ./docker/nginx/templates:/etc/nginx/templates
      - ${APP_PATH_WWW}:/var/www

  mysql:
    build:
      context: ./docker/mysql
      args:
        - MYSQL_DATABASE=${APP_NAME}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    container_name: ${APP_NAME}_mysql
    environment:
      - MYSQL_DATABASE=${APP_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    hostname: ${APP_NAME}_mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - ./opt:/opt
      - ./log:/var/log
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql

  php:
    build:
      context: ./docker/php
      args:
        - PHP_VERSION=${PHP_VERSION:-7.4.16}
        - PHP_SYSTEM_TZ=${PHP_SYSTEM_TZ:-Europe/London}
    container_name: ${APP_NAME}_php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:${MYSQL_PORT}/${APP_NAME}?serverVersion=5.7
    hostname: ${APP_NAME}_php
    volumes:
      - ./opt:/opt
      - ./log:/var/log
      - ${APP_PATH_WWW}:/var/www

networks:
  default:
    name: ${APP_NAME}
