services:

    nginx:
        hostname: nginx
        build:
          context: ./nginx
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./nginx/conf.d/:/etc/nginx/conf.d
          - ./nginx/sites/:/etc/nginx/sites-available
          - ../log:/var/log
          - ../www:/var/www
        depends_on:
          - php-fpm
        ports:
          - "${HTTP_PORT}:80"
          - "${HTTPS_PORT}:443"

    mysql:
        hostname: mysql
        build:
          context: ./mysql
        environment:
          - MYSQL_DATABASE=${MYSQL_NAME}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
          - "${MYSQL_PORT}:3306"
        volumes:
          - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
          - ./mysql/data:/var/lib/mysql

    php-fpm:
        hostname: php-fpm
        build:
          context: ./php-fpm
        environment:
          - APP_ENV=${APP_ENV}
          - APP_SECRET=${APP_SECRET}
          - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:${MYSQL_PORT}/${MYSQL_NAME}?serverVersion=5.7
        volumes:
          - ../www:/var/www
